package kappalekirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kappalekirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.07.26 08:55:26 // Generated by ComTest
 *
 */
public class KappaleetTest {



  // Generated by ComTest BEGIN
  /** testLisaa70 */
  @Test
  public void testLisaa70() {    // Kappaleet: 70
    Kappaleet kappaleet = new Kappaleet(); 
    Kappale a = new Kappale(), b = new Kappale(); 
    assertEquals("From: Kappaleet line: 73", 0, kappaleet.getLkm()); ; 
    kappaleet.lisaa(a); assertEquals("From: Kappaleet line: 74", 1, kappaleet.getLkm()); 
    kappaleet.lisaa(b); assertEquals("From: Kappaleet line: 75", 2, kappaleet.getLkm()); 
    kappaleet.lisaa(a); assertEquals("From: Kappaleet line: 76", 3, kappaleet.getLkm()); 
    assertEquals("From: Kappaleet line: 77", a, kappaleet.anna(0)); 
    assertEquals("From: Kappaleet line: 78", b, kappaleet.anna(1)); 
    assertEquals("From: Kappaleet line: 79", a, kappaleet.anna(2)); 
    assertEquals("From: Kappaleet line: 80", false, kappaleet.anna(1) == a); 
    assertEquals("From: Kappaleet line: 81", true, kappaleet.anna(1) == b); 
    try {
    assertEquals("From: Kappaleet line: 82", a, kappaleet.anna(3)); 
    fail("Kappaleet: 82 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kappaleet.lisaa(a); assertEquals("From: Kappaleet line: 83", 4, kappaleet.getLkm()); 
    kappaleet.lisaa(b); assertEquals("From: Kappaleet line: 84", 5, kappaleet.getLkm()); 
    kappaleet.lisaa(a); assertEquals("From: Kappaleet line: 85", 6, kappaleet.getLkm()); 
  } // Generated by ComTest END
}