package kappalekirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kappalekirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.07.26 08:55:43 // Generated by ComTest
 *
 */
public class VersioTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi221 */
  @Test
  public void testRekisteroi221() {    // Versio: 221
    Versio a = new Versio(); 
    Versio b = new Versio(); 
    assertEquals("From: Versio line: 224", 0, a.getVersioTunnus()); 
    a.rekisteroi(); 
    b.rekisteroi(); 
    a.rekisteroi(); 
    int n1 = a.getVersioTunnus(); 
    int n2 = b.getVersioTunnus(); 
    assertEquals("From: Versio line: 230", n2-1, n1); 
  } // Generated by ComTest END
}