package kappalekirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import kappalekirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.07.26 08:55:51 // Generated by ComTest
 *
 */
public class VersiotTest {



  // Generated by ComTest BEGIN
  /** testGetLkm87 */
  @Test
  public void testGetLkm87() {    // Versiot: 87
    Versiot versiot = new Versiot(); 
    Versio a = new Versio(); 
    Versio b = new Versio(); 
    a.rekisteroi(); 
    b.rekisteroi(); 
    assertEquals("From: Versiot line: 93", 0, versiot.getLkm()); 
    versiot.lisaa(a); 
    assertEquals("From: Versiot line: 95", 1, versiot.getLkm()); 
    versiot.lisaa(b); 
    assertEquals("From: Versiot line: 97", 2, versiot.getLkm()); 
    versiot.lisaa(a); 
    versiot.lisaa(b); 
    assertEquals("From: Versiot line: 100", 4, versiot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaVersiot112 */
  @Test
  public void testAnnaVersiot112() {    // Versiot: 112
    Versiot versiot = new Versiot(); 
    Versio a2 = new Versio(2); versiot.lisaa(a2); 
    Versio b1 = new Versio(1); versiot.lisaa(b1); 
    Versio a1 = new Versio(1); versiot.lisaa(a1); 
    Versio b2 = new Versio(2); versiot.lisaa(b2); 
    Versio c1 = new Versio(1); versiot.lisaa(c1); 
    Versio a3 = new Versio(3); versiot.lisaa(a3); 
    List<Versio> loytyneet; 
    loytyneet = versiot.annaVersiot(4); 
    assertEquals("From: Versiot line: 125", 0, loytyneet.size()); 
    loytyneet = versiot.annaVersiot(1); 
    assertEquals("From: Versiot line: 127", 3, loytyneet.size()); 
    assertEquals("From: Versiot line: 128", true, loytyneet.get(0) == b1); 
    assertEquals("From: Versiot line: 129", true, loytyneet.get(1) == a1); 
    loytyneet = versiot.annaVersiot(2); 
    assertEquals("From: Versiot line: 131", 2, loytyneet.size()); 
    loytyneet = versiot.annaVersiot(3); 
    assertEquals("From: Versiot line: 133", 1, loytyneet.size()); 
    assertEquals("From: Versiot line: 134", true, loytyneet.get(0) == a3); 
  } // Generated by ComTest END
}